modLoader = "javafml"
loaderVersion = "[40,)"
#issueTrackerURL = ""
license = "ARR"
issueTrackerURL = "https://github.com/MehVahdJukaar/Moonlight/issues" #optional

[[mods]]
modId = "moonlight"
version = "${version}"
displayName = "Moonlight Library"
authors = "MehVahdJukaar"
modUrl = "https://www.curseforge.com/minecraft/mc-mods/selene" #optional
updateJSONURL = "https://raw.githubusercontent.com/MehVahdJukaar/Moonlight/master/forge/update.json"

logoFile="icon.png" #optional
description = '''
A small library with many cool unique features, from dynamic asset generation to dynamic villager schedules and multi loader utilities
'''
#logoFile = ""

[[dependencies.moonlight]]
modId = "forge"
mandatory = true
versionRange = "[43.1.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.moonlight]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.1,)"
ordering = "NONE"
side = "BOTH"
