
modLoader="javafml" #mandatory

loaderVersion="[38,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

issueTrackerURL="https://www.curseforge.com/minecraft/mc-mods/selene/issues" #optional

[[mods]] #mandatory

    modId="moonlight" #mandatory

    version="${file.jarVersion}" #mandatory

    displayName="Moonlight" #mandatory

    displayURL="https://www.curseforge.com/minecraft/mc-mods/selene" #optional

    logoFile="icon.png" #optional

    logoBlur = false

    itemIcon="minecraft:end_stone" #catalogue icon

    credits="" #optional

    authors="MehVahdJukaar" #optional

    description='''
    A small library that allows to make custom map markers, first and third person animations and contains the soft fluid system as well as other utilities
    '''


[[dependencies.moonlight]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[40.0.36,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.moonlight]]

    modId="minecraft"

    mandatory=true

    versionRange="[1.19,1.20)"

    ordering="NONE"

    side="BOTH"
